"""Render a continuous Canadian wildfire map using FireStat's source pipeline.

Requires FireStat's Python environment and downloaded NFDB archive. No network
calls are made: the Statistics Canada geometries must already be cached.
"""
import argparse
import importlib.util
import json
import math
import time
from pathlib import Path

import geopandas as gpd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import pandas as pd
import pyogrio
import shapely
from PIL import Image


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source-project', required=True, type=Path)
    parser.add_argument('--archive', required=True, type=Path)
    parser.add_argument('--cache', required=True, type=Path)
    parser.add_argument('--output', required=True, type=Path)
    parser.add_argument('--width', default=3600, type=int)
    parser.add_argument('--tiles', action='store_true')
    args = parser.parse_args()
    # Only open images generated by this script, including the large tile source.
    Image.MAX_IMAGE_PIXELS = None
    started = time.perf_counter()
    spec = importlib.util.spec_from_file_location('firestat_atlas', args.source_project / 'scripts/build_canada_fire_atlas.py')
    source = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(source)
    args.cache.mkdir(parents=True, exist_ok=True)
    args.output.mkdir(parents=True, exist_ok=True)
    provinces = gpd.read_file(args.source_project / 'data/canada_province_boundaries_2021.gpkg').to_crs(source.SOURCE_CRS)
    centres = gpd.read_file(args.source_project / 'data/canada_population_centres_2021.gpkg').to_crs(source.SOURCE_CRS)
    cache = args.cache / 'national-perimeters-250m.gpkg'
    if cache.exists():
        fires = gpd.read_file(cache)
        print(f'Loaded {len(fires):,} cached incident perimeters', flush=True)
    else:
        print('Preparing the national land boundary', flush=True)
        land = shapely.union_all(shapely.make_valid(
            provinces.geometry.simplify(250, preserve_topology=False).array,
            method='structure', keep_collapsed=False))
        frames = []
        # FireStat's original loader uses a province window and an intersection
        # test. A national pass does not need that repeated spatial filtering.
        # Simplify in the target metre-based CRS before merging to bound memory.
        for layer in source.archive_layers(args.archive):
            print(f'Reading {Path(layer).name}', flush=True)
            frame = pyogrio.read_dataframe(layer, where='YEAR >= 1980 AND YEAR <= 2024',
                columns=['SRC_AGENCY', 'FIRE_ID', 'YEAR', 'SIZE_HA'])
            print(f'Projecting and simplifying {len(frame):,} source polygons', flush=True)
            frame = frame.to_crs(source.SOURCE_CRS)
            simplified = frame.geometry.simplify(250, preserve_topology=False)
            # Preserve small perimeters that would otherwise disappear entirely.
            collapsed = simplified.is_empty
            simplified.loc[collapsed] = frame.loc[collapsed].geometry.simplify(250, preserve_topology=True)
            frame.geometry = shapely.make_valid(simplified.array, method='structure', keep_collapsed=False)
            frame = frame[~frame.geometry.is_empty & ~frame.geometry.isna()].copy()
            frames.append(frame)
        fires = gpd.GeoDataFrame(pd.concat(frames, ignore_index=True), crs=source.SOURCE_CRS)
        del frames
        ids = fires.FIRE_ID.fillna('').astype(str).str.strip()
        keys = fires.SRC_AGENCY.astype(str) + ':' + fires.YEAR.astype(str) + ':' + ids
        fires['incident_key'] = keys.where(ids.ne(''), 'row:' + fires.index.astype(str))
        duplicate = fires.incident_key.duplicated(keep=False)
        print(f'Merging {duplicate.sum():,} component records by agency/year/fire ID', flush=True)
        if duplicate.any():
            merged = fires[duplicate].dissolve(by='incident_key', as_index=False, aggfunc='first')
            fires = gpd.GeoDataFrame(pd.concat([fires[~duplicate], merged], ignore_index=True), crs=source.SOURCE_CRS)
        print(f'Clipping {len(fires):,} incident perimeters to Canada', flush=True)
        # Most incidents are completely inside Canada. A prepared containment
        # test avoids intersecting each one with every island and coastline.
        shapely.prepare(land)
        inside = shapely.covers(land, fires.geometry.array)
        intersects = shapely.intersects(land, fires.geometry.array)
        print(f'{inside.sum():,} interior records; {(~inside & intersects).sum():,} boundary intersections', flush=True)
        fires = fires[intersects].copy()
        needs_clip = ~shapely.covers(land, fires.geometry.array)
        fires.loc[needs_clip, 'geometry'] = shapely.intersection(fires.loc[needs_clip].geometry.array, land)
        fires = fires[~fires.geometry.is_empty].copy()
        fires.to_file(cache, driver='GPKG')
        print(f'Cached {len(fires):,} nationally clipped incident perimeters', flush=True)
    xmin, ymin, xmax, ymax = provinces.total_bounds
    pad = (xmax - xmin) * .025
    xmin, ymin, xmax, ymax = xmin-pad, ymin-pad, xmax+pad, ymax+pad
    height = round(args.width * (ymax-ymin)/(xmax-xmin))
    print(f'Rendering {args.width} × {height}', flush=True)
    fig = plt.figure(figsize=(args.width/200, height/200), dpi=200, facecolor='#fafafa')
    ax = fig.add_axes([0,0,1,1])
    # Keep line widths in image pixels, independent of output resolution.
    provinces.plot(ax=ax, facecolor='#e7e8e6', edgecolor='none', zorder=1)
    fires.plot(ax=ax, facecolor='#bf3530', edgecolor='none', alpha=.23, zorder=2)
    provinces.boundary.plot(ax=ax, color='#9b9f9e', linewidth=.22, zorder=3)
    ax.set_xlim(xmin,xmax); ax.set_ylim(ymin,ymax); ax.set_aspect('equal'); ax.axis('off')
    raster = args.output / 'canada-map.png'
    fig.savefig(raster, dpi=200, facecolor='#fafafa')
    plt.close(fig)
    wanted = {'Vancouver','Victoria','Kelowna','Kamloops','Prince George','Fort St. John','Calgary','Edmonton','Fort McMurray','Saskatoon','Regina','Prince Albert','La Ronge','Winnipeg','Thompson','Brandon','Toronto','Ottawa - Gatineau','Thunder Bay','Kenora','Dryden','Montréal','Québec','Chicoutimi - Jonquière','Moncton','Fredericton','Halifax','Charlottetown',"St. John's",'Happy Valley-Goose Bay','Whitehorse','Dawson','Yellowknife','Inuvik','Iqaluit','Arviat'}
    labels=[]
    for _, row in centres[centres.PCNAME.isin(wanted)].sort_values('population_2021',ascending=False).drop_duplicates('PCNAME').iterrows():
        point=row.geometry.representative_point()
        labels.append({'name':row.PCNAME,'x':round((point.x-xmin)/(xmax-xmin),7),'y':round((ymax-point.y)/(ymax-ymin),7),'population':int(row.population_2021)})
    metadata={'title':'Canadian Wildfire Atlas','year_range':[1980,2024],'width':args.width,'height':height,'crs':source.SOURCE_CRS,'bounds':[xmin,ymin,xmax,ymax],'incident_perimeters':len(fires),'simplification_metres':250,'archive_edition':'2026-01-28','source_retrieved_on':'2026-10-03','fire_source':source.FIRE_URL,'boundary_source':source.BOUNDARY_URL,'labels':labels}
    with Image.open(raster) as image:
        image.thumbnail((2400,2400))
        image.save(args.output/'canada-preview.webp',quality=90)
        image.save(args.output/'canada-preview.png',optimize=True)
        image.thumbnail((800,800))
        image.save(args.output/'canada-preview-800.webp',quality=90)
    if args.tiles:
        Image.MAX_IMAGE_PIXELS = None
        with Image.open(raster) as original:
            original=original.convert('RGB')
            maximum=math.ceil(math.log2(max(original.size)))
            count=0
            for level in range(maximum+1):
                divisor=2**(maximum-level)
                size=(math.ceil(args.width/divisor),math.ceil(height/divisor))
                scaled=original.resize(size, Image.Resampling.LANCZOS) if divisor>1 else original
                directory=args.output/'canada_files'/str(level)
                directory.mkdir(parents=True,exist_ok=True)
                for x in range(math.ceil(size[0]/512)):
                    for y in range(math.ceil(size[1]/512)):
                        # 1-pixel overlap prevents visible seams while zooming.
                        box=(max(0,x*512-1),max(0,y*512-1),min(size[0],(x+1)*512+1),min(size[1],(y+1)*512+1))
                        scaled.crop(box).save(directory/f'{x}_{y}.webp',quality=90)
                        count+=1
                if divisor>1: scaled.close()
            metadata.update({'tile_count':count,'tile_size':512,'tile_overlap':1})
        (args.output/'canada.dzi').write_text(f'<Image TileSize="512" Overlap="1" Format="webp" xmlns="http://schemas.microsoft.com/deepzoom/2008"><Size Width="{args.width}" Height="{height}"/></Image>\n')
        print(f'Created {count} tiles',flush=True)
    metadata['build_seconds']=round(time.perf_counter()-started,1)
    (args.output/'national-manifest.json').write_text(json.dumps(metadata,indent=2,ensure_ascii=False)+'\n')
    print(f'Finished in {metadata["build_seconds"]} seconds: {raster}',flush=True)

if __name__=='__main__': main()
